### ISSUE TITLE
Amount of fps while recording

### ISSUE THREAD

**Issue by yuvalkh** [capi-bgu/capi#21]
In the current fps (2) we will get 6GB of pictures per user after use of 21 days 2 hours per day.
Might want to decrease it to 1GB of pictures per user, like reducing the fps to 0.33 fps.

**Comment by Zshoham** [comment]
This should be up to the "user" for every run.
for example, if we are doing the short 1-2 hour experiments 2 fps might be good. We might even want to record at higher fps so we will be able to compare results for different fps.
If we run the longer experiments we might need to reduce the fps, but it doesn't need to be a constant.
