### ISSUE TITLE
Create UI for the system

### ISSUE THREAD

**Issue by hodTwito** [capi-bgu/capi#31]
Create nice and easy to use GUI for the system, and integrate it to our current system.

- [x] Generically collect different type of labels, and explain every type.
- [x] Get new labels
- [x] Self called report for new label
- [x] Register with user details for experiments statistics.

**Comment by Zshoham** [comment]
the UI can be found in a new repository dedicated to it, [here](https://github.com/capi-bgu/capi-desktop)
